### PR TITLE
Fix DOCKER_BUILDKIT=0 by default to support docker versions >= 23

### PR DESCRIPTION
**Pull request by mathieucarbou**

### CODE REVIEW

**Comment by akomakom** [comment]
FYI, We currently have this set globally in CI

**Comment by mathieucarbou** [comment]
@akomakom : I agree, this is not meant to change the build system but to have a consistant build behaviour everywhere, also on dev computers ;-)

yes, this does not remove the fact that one day someone will have to refactor our docker builds... But this is a bigger task while this will allow to use docker v23 and more, which is not what's coming by default

**Comment by akomakom** [comment]
If this is exclusively for developer use, should this be done in a gradle init plugin instead?  
Thougts from @chrisdennis ?

**Comment by chrisdennis** [comment]
imho this belongs in the convention plugin. This means this PR would likely morph in to one where we expose the environment of a DockerTask and then the convention plugin can set it appropriately.

**Pull request closed without merging**
